# -*- coding: utf-8 -*-
"""AI Text Summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mKeg8hWSZ9AIt1saTvDGg3_VC28ZHExK
"""

!pip install gradio transformers nltk

import gradio as gr
from transformers import pipeline
import nltk

nltk.download('punkt')

summarizer = pipeline("summarization")

def summarize_text(text):
    if len(text) < 50:
        return "⚠️ Text is too short to summarize. Please enter a longer text."

    summary = summarizer(text, max_length=150, min_length=50, do_sample=False)
    return summary[0]['summary_text']

interface = gr.Interface(
    fn=summarize_text,
    inputs=gr.Textbox(lines=5, placeholder="📝 Enter text to summarize..."),
    outputs="text",
    title="📝 AI Text Summarizer",
    description="Enter a long paragraph, and the AI will generate a concise summary.",
)

interface.launch()